version: "3.8"

services:
  api-gateway:
    extends:
      file: ./services/api-gateway.yml
      service: api-gateway
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy

  auth-service:
    extends:
      file: ./services/auth-service.yml
      service: auth-service
    depends_on:
      postgres:
        condition: service_healthy

  user-service:
    extends:
      file: ./services/user-service.yml
      service: user-service
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    extends:
      file: ./services/mysql.yml
      service: mysql

  postgres:
    extends:
      file: ./services/postgres.yml
      service: postgres

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local

networks:
  microservices-network:
    driver: bridge
