services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    expose:
      - "8081"
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER:-user}
      - DB_PASSWORD=${MYSQL_PASSWORD:-password}
      - DB_NAME=${MYSQL_DATABASE:-userdb}
      - DB_PORT=3306
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 